name: Pull Request Auto Merge To Dev
on:
  # 推送代码后触发
  pull_request:
    types:
      - closed
    branches:
      - stable

jobs:
  merge_pull_request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Auto merge to staging
        run: |
          git fetch origin staging
          git checkout staging
          git merge --no-edit ${{ github.base_ref }}
          git push origin staging
